### PR TITLE
Filter ops

### PR DESCRIPTION
**Pull request by paulprozesky**
@brickZA - so what do we do when it won't merge automatisch?

### CODE REVIEW

**Comment by brickZA** [comment]
One way is to make sure your devel branch is up to date on your local repo, checkout out filter_ops, saying 'git merge devel', and fixing the conflicts. Git should tell you what to do at each step. When done, push to github, and mergy-merge should go green.

**Comment by paulprozesky** [comment]
That's so odd, because that's exactly what I did. Said all was well. then when I committed everything and tried to make the pull request, it said it couldn't be done. Anyway, chat Monday.

**Comment by paulprozesky** [comment]
NVM, figured it out. Fixing conflicts.

**Comment by paulprozesky** [comment]
So merged, @brickZA

**Pull request merged**
